services:
  mongo:
    image: mongo
    hostname: "mongo"
    container_name: 'mongo_methodology'
    volumes:
      - ./.docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${trabajo}
      MONGO_INITDB_ROOT_USERNAME: ${trabajo}
      MONGO_INITDB_ROOT_PASSWORD: ${M7EENmRlLJMYqQyh}
    ports:
      - "27017:27017"