ktor:
    application:
        modules:
            - utn.methodology.ApplicationKt.module
    deployment:
        port: 8080

db:
    mongo:
        user: 'trabajo'
        password: 'M7EENmRlLJMYqQyh'